import "./global.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Hello NextJs",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <AntdRegistry>{children}</AntdRegistry>
        </main>
      </body>
    </html>
  );
}
