import GlobalLayout from "../components/Layout";

export const metadata = {
  title: "Hello NextJs",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <GlobalLayout>{children}</GlobalLayout>;
}
